// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__Nullable from "@rescript/core/src/Core__Nullable.res.mjs";

var prefix = "OOC_MSGS";

function getOoc() {
  var data = channelCustomData.get(prefix);
  var cdata = Core__Nullable.getOr(data, {
        currentId: 0,
        messages: []
      });
  if (cdata.messages.length === 0) {
    return {
            TAG: "Error",
            _0: "NoMessages"
          };
  } else {
    return {
            TAG: "Ok",
            _0: cdata
          };
  }
}

var ChannelCustomData = {
  getOoc: getOoc
};

var Utils = {};

export {
  prefix ,
  ChannelCustomData ,
  Utils ,
}
/* No side effect */
