// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";

var prefix = "OOC_MSGS";

function getOoc() {
  var data = channelCustomData.get(prefix);
  var cdata = Core__Option.getOr((data == null) ? undefined : Caml_option.some(data), {
        currentId: 0,
        messages: []
      });
  if (cdata.messages.length === 0) {
    return {
            TAG: "Error",
            _0: "NoMessages"
          };
  } else {
    return {
            TAG: "Ok",
            _0: cdata
          };
  }
}

var ChannelCustomData = {
  getOoc: getOoc
};

var Utils = {};

export {
  prefix ,
  ChannelCustomData ,
  Utils ,
}
/* No side effect */
