// Generated by ReScript, PLEASE EDIT WITH CARE


var prefix = "OOC_MSGS";

function getOoc() {
  var data = channelCustomData.get(prefix);
  if (data == null) {
    return {
            TAG: "Error",
            _0: "NoData"
          };
  } else if (data.messages.length === 0) {
    return {
            TAG: "Error",
            _0: "NoMessages"
          };
  } else {
    return {
            TAG: "Ok",
            _0: data
          };
  }
}

function initOoc() {
  channelCustomData.set(prefix, {
        currentId: 0,
        messages: []
      });
}

function oocErrorToStr(err) {
  if (err === "NoMessages") {
    return "It seems like there is initialised data but no messages. Try adding some messages with $$ooc add […]";
  } else {
    return "Seems like you're running the command for the first time, I initialised some data, try adding a message with $$ooc add";
  }
}

var ChannelCustomData = {
  getOoc: getOoc,
  initOoc: initOoc,
  oocErrorToStr: oocErrorToStr
};

var Utils = {};

export {
  prefix ,
  ChannelCustomData ,
  Utils ,
}
/* No side effect */
